### ISSUE TITLE
Can't install Mouse Fast Scroll in VS 17.0.3172-preview3

### ISSUE THREAD

**Issue by dmitrybv** [tunnelvisionlabs/MouseFastScroll#33]
Hello 

Can't install Mouse Fast Scroll in VS 17.0.3172-preview3

Here is VSIX Installer Log:
```
g8/09/2021 23:03:02 - Microsoft VSIX Installer
8/09/2021 23:03:02 - -------------------------------------------
8/09/2021 23:03:02 - vsixinstaller.exe version:
8/09/2021 23:03:02 - 17.0.3172-preview3
8/09/2021 23:03:02 - -------------------------------------------
8/09/2021 23:03:02 - Command line parameters:
8/09/2021 23:03:02 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Tmp\EhLib\Tvl.VisualStudio.MouseFastScroll.vsix
8/09/2021 23:03:02 - -------------------------------------------
8/09/2021 23:03:02 - Microsoft VSIX Installer
8/09/2021 23:03:02 - -------------------------------------------
8/09/2021 23:03:02 - Initializing Install...
8/09/2021 23:03:03 - Extension Details...
8/09/2021 23:03:03 - 	Identifier         : Tvl.VisualStudio.MouseFastScroll.7DFA0DD1-8052-464D-9A1A-5EADC10A84B0
8/09/2021 23:03:03 - 	Name               : Mouse Fast Scroll
8/09/2021 23:03:03 - 	Author             : Sam Harwell
8/09/2021 23:03:03 - 	Version            : 4.3.0
8/09/2021 23:03:03 - 	Description        : Use Ctrl+Mouse Wheel for fast and easy Page Up/Down scrolling.
8/09/2021 23:03:03 - 	Locale             : en-US
8/09/2021 23:03:03 - 	MoreInfoURL        : https://github.com/tunnelvisionlabs/MouseFastScroll
8/09/2021 23:03:03 - 	InstalledByMSI     : False
8/09/2021 23:03:03 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
8/09/2021 23:03:03 - 
8/09/2021 23:03:03 - 	SignatureState     : Unsigned
8/09/2021 23:03:03 - 	Supported Products : 
8/09/2021 23:03:03 - 		Microsoft.VisualStudio.Community
8/09/2021 23:03:03 - 			Version : [11.0,18.0)
8/09/2021 23:03:03 - 			ProductArchitecture : notSpecified
8/09/2021 23:03:03 - 		Microsoft.VisualStudio.Pro
8/09/2021 23:03:03 - 			Version : [11.0,18.0)
8/09/2021 23:03:03 - 			ProductArchitecture : notSpecified
8/09/2021 23:03:03 - 
8/09/2021 23:03:03 - 	References         : 
8/09/2021 23:03:03 - 	Prerequisites      : 
8/09/2021 23:03:03 - 		-------------------------------------------------------
8/09/2021 23:03:03 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
8/09/2021 23:03:03 - 		Name         : Visual Studio core editor
8/09/2021 23:03:03 - 		Version      : [15.0,18.0)
8/09/2021 23:03:03 - 
8/09/2021 23:03:03 - Signature Details...
8/09/2021 23:03:03 - 	Extension is not signed.
8/09/2021 23:03:03 - 
8/09/2021 23:03:03 - Searching for applicable products...
8/09/2021 23:03:03 - Found installed product - Microsoft Visual Studio Express 2012 for Windows Desktop
8/09/2021 23:03:03 - Found installed product - Microsoft Visual Studio Community 2015
8/09/2021 23:03:03 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
8/09/2021 23:03:03 - Found installed product - Global Location
8/09/2021 23:03:03 - Found installed product - Visual Studio Community 2019
8/09/2021 23:03:03 - Found installed product - Visual Studio Community 2022 Preview
8/09/2021 23:03:03 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

**Comment by RobLinux** [comment]
https://github.com/tunnelvisionlabs/MouseFastScroll/pull/34

**Comment by sharwell** [comment]
This was already fixed by #32 but is not yet published
